apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  keycloak_issuer: "https://zany-tribble-jj9jrxg5v55jhp9w4-8080.app.github.dev/realms/auth101"
  keycloak_url: "https://zany-tribble-jj9jrxg5v55jhp9w4-8080.app.github.dev"
  keycloak_realm: "auth101"
  keycloak_client_id: "my-spa-app"
  allowed_origins: "*"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-casbin-config
data:
  model.conf: |
    [request_definition]
    r = sub, obj, act

    [policy_definition]
    p = sub, obj, act

    [role_definition]
    g = _, _

    [policy_effect]
    e = some(where (p.eft == allow))

    [matchers]
    m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
  policy.csv: |
    p, admin, /api/data, GET
    p, teacher, /api/data, GET