apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
stringData:
  keycloak_public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhVpkIC+zXBM4sFug3e7fMKYX
    8b+zXEJvPe1fRvthnG2a7xzOaIl8OXwgO3ldpFR576cAP1vNMEhI97kZ6vovm2YYtvm/
    yWJgKLPmEoRa3hxtoilcLA4PfPFJvYuf09RCHIFlzSXa2Up3h2uywLSPPAwkELfQKL1s
    MZitCfxp/JUXxCF5Kdjqg9EEgeXVXcBfizApUm1okZJKT+n7EQ3Ys0XdjkPgiEUUjw6S
    qrtEntcbniU6BfNjl/8GT/n9AThJDNlB+cgusXoA9WSdik0x8Mx8JNPDwWvVA0yaYBsT
    mHM1u1G+L9+G/lhtUnIWKt/0zilPmuneQyI+F5PmYQA7RwIDAQAB
    -----END PUBLIC KEY-----